### ISSUE TITLE
Home Assistant

### ISSUE THREAD

**Issue by KreonNoerk1987** [micw/tibber-meter-uploader#4]
Ist es auch möglich den Zählerstand über Home Assistant an Tibber zu senden?

**Comment by micw** [comment]
Moin. Prinzipiell erlaubt mein Tool alle möglichen Quellen. Allerdings ist es immer als externes Tool aufzurufen, ich habe nicht vor, es irgendwo zu integrieren. Wie liegen die Daten denn im HomeAssistant vor?

**Comment by KreonNoerk1987** [comment]
Ich habe einen normalen Sensor, wo der Zählerstand als Wert drin steht. Dieser wird direkt aus dem Stromzähler ausgelesen. Das ist aber mein kleinstes Problem. Sobald ich das Programm ausführe (lokal per jar Datei oder als Docker), es bricht immer mit folgender Fehlermeldung ab:

`2023-03-01 19:25:55.543  INFO 24 --- [           main] de.wyraz.tibberuploader.TibberUploader   : Starting TibberUploader v1.0.0-SNAPSHOT using Java 17-ea on 497c0ae370f3 with PID 24 (/tibber-meter-uploader-1.0.0-SNAPSHOT.jar started by root in /)
2023-03-01 19:25:55.546  INFO 24 --- [           main] de.wyraz.tibberuploader.TibberUploader   : No active profile set, falling back to 1 default profile: "default"
2023-03-01 19:26:03.802  INFO 24 --- [           main] de.wyraz.tibberuploader.TibberUploader   : Started TibberUploader in 11.685 seconds (JVM running for 26.133)
2023-03-01 19:26:07.418  INFO 24 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2023-03-01 19:26:07.438 ERROR 24 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: Failed to execute CommandLineRunner
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:820) ~[spring-boot-2.5.14.jar!/:2.5.14]
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:801) ~[spring-boot-2.5.14.jar!/:2.5.14]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:350) ~[spring-boot-2.5.14.jar!/:2.5.14]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1370) ~[spring-boot-2.5.14.jar!/:2.5.14]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1359) ~[spring-boot-2.5.14.jar!/:2.5.14]
        at de.wyraz.tibberuploader.TibberUploader.main(TibberUploader.java:28) ~[classes!/:1.0.0-SNAPSHOT]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[tibber-meter-uploader-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[tibber-meter-uploader-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[tibber-meter-uploader-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[tibber-meter-uploader-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
Caused by: java.lang.IllegalArgumentException: Meter e97c3e69-f6dc-44fa-85c5-ccf94dba73bf has no register with id '1-0:1.8.0'. Available registers are: 1-1:1.8.0
        at de.wyraz.tibberuploader.tibber.InternalAccountInfoResponse$AccountInfoMeter.unwrap(InternalAccountInfoResponse.java:104) ~[classes!/:1.0.0-SNAPSHOT]
        at de.wyraz.tibberuploader.tibber.InternalAccountInfoResponse$AccountInfoMe.unwrap(InternalAccountInfoResponse.java:45) ~[classes!/:1.0.0-SNAPSHOT]
        at de.wyraz.tibberuploader.tibber.InternalAccountInfoResponse.unwrap(InternalAccountInfoResponse.java:15) ~[classes!/:1.0.0-SNAPSHOT]
        at de.wyraz.tibberuploader.tibber.TibberPrivateApi.getAccoutInfo(TibberPrivateApi.java:123) ~[classes!/:1.0.0-SNAPSHOT]
        at de.wyraz.tibberuploader.TibberUploader.uploadMissingReadings(TibberUploader.java:52) ~[classes!/:1.0.0-SNAPSHOT]
        at de.wyraz.tibberuploader.TibberUploader.run(TibberUploader.java:43) ~[classes!/:1.0.0-SNAPSHOT]
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:817) ~[spring-boot-2.5.14.jar!/:2.5.14]
        ... 13 common frames omitted
`

Kannst du mir da helfen?

**Comment by micw** [comment]
Keine Rückmeldung, ich schließe das mal. Bei Bedarf einfach ein neues Ticket aufmachen.

**Comment by PulsarFX** [comment]
> Schau mal weiter unten in der Fehlermeldung (ich sollte die Anzeige mal verbessern).
> 
> https://github.com/micw/tibber-meter-uploader#meter-register-id

in der verlinkten Doku steht zwei mal das Gleiche:
"In einigen Fällen ist bei Tibber nicht der Standard-OBIS-Code 1-1:1.8.0 für den Gesamt-Strombezug hinterlegt sondern 1-1:1.8.0"
