### ISSUE TITLE
Container schmiert ab beim starten

### ISSUE THREAD

**Issue by theeogflip** [micw/tibber-meter-uploader#6]
Hi,
ich habe 2 Docker Container für 2 Zähler am laufen.

Bis letzte woche lief alles top.

nun gibt ein Container einen Fehler, obwohl der andere ohne probleme weiter läuft.

Ich habe ihn schon neu aufgesetzt, aber dennoch komme ich nicht weiter :/ 

Beim Starten geht er gleich wieder weg..

` .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::               (v2.5.14)

2023-09-04 12:48:17.156  INFO 22 --- [           main] de.wyraz.tibberuploader.TibberUploader   : Starting TibberUploader v1.0.0-SNAPSHOT using Java 17-ea on 0111dd7ee01a with PID 22 (/tibber-meter-uploader-1.0.0-SNAPSHOT.jar started by root in /)
2023-09-04 12:48:17.168  INFO 22 --- [           main] de.wyraz.tibberuploader.TibberUploader   : No active profile set, falling back to 1 default profile: "default"
2023-09-04 12:48:21.922  INFO 22 --- [           main] de.wyraz.tibberuploader.TibberUploader   : Started TibberUploader in 6.666 seconds (JVM running for 8.195)
2023-09-04 12:48:23.532  INFO 22 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2023-09-04 12:48:23.597 ERROR 22 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: Failed to execute CommandLineRunner
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:820) ~[spring-boot-2.5.14.jar!/:2.5.14]
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:801) ~[spring-boot-2.5.14.jar!/:2.5.14]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:350) ~[spring-boot-2.5.14.jar!/:2.5.14]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1370) ~[spring-boot-2.5.14.jar!/:2.5.14]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1359) ~[spring-boot-2.5.14.jar!/:2.5.14]
        at de.wyraz.tibberuploader.TibberUploader.main(TibberUploader.java:28) ~[classes!/:1.0.0-SNAPSHOT]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[tibber-meter-uploader-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[tibber-meter-uploader-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[tibber-meter-uploader-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[tibber-meter-uploader-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "errors" (class de.wyraz.tibberuploader.tibber.InternalAccountInfoResponse), not marked as ignorable (one known property: "data"])
 at [Source: (org.apache.http.client.entity.LazyDecompressingInputStream); line: 1, column: 12] (through reference chain: de.wyraz.tibberuploader.tibber.InternalAccountInfoResponse["errors"])
        at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61) ~[jackson-databind-2.12.6.1.jar!/:2.12.6.1]
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:987) ~[jackson-databind-2.12.6.1.jar!/:2.12.6.1]
        at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1974) ~[jackson-databind-2.12.6.1.jar!/:2.12.6.1]
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1701) ~[jackson-databind-2.12.6.1.jar!/:2.12.6.1]
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1679) ~[jackson-databind-2.12.6.1.jar!/:2.12.6.1]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:330) ~[jackson-databind-2.12.6.1.jar!/:2.12.6.1]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:187) ~[jackson-databind-2.12.6.1.jar!/:2.12.6.1]
        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322) ~[jackson-databind-2.12.6.1.jar!/:2.12.6.1]
        at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:2033) ~[jackson-databind-2.12.6.1.jar!/:2.12.6.1]
        at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1426) ~[jackson-databind-2.12.6.1.jar!/:2.12.6.1]
        at de.wyraz.tibberuploader.tibber.TibberPrivateApi.getAccoutInfo(TibberPrivateApi.java:122) ~[classes!/:1.0.0-SNAPSHOT]
        at de.wyraz.tibberuploader.TibberUploader.uploadMissingReadings(TibberUploader.java:52) ~[classes!/:1.0.0-SNAPSHOT]
        at de.wyraz.tibberuploader.TibberUploader.run(TibberUploader.java:43) ~[classes!/:1.0.0-SNAPSHOT]
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:817) ~[spring-boot-2.5.14.jar!/:2.5.14]
        ... 13 common frames omitted

** Drücke eine BELIEBIGE TASTE, um dieses Fenster zu schließen ** `

**Comment by micw** [comment]
Da ist offenbar ein Feld "errors" dazugekommen.

`Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "errors" (class de.wyraz.tibberuploader.tibber.InternalAccountInfoResponse), not marked as ignorable (one known property: "data"])
at [Source: (org.apache.http.client.entity.LazyDecompressingInputStream); line: 1, column: 12] (through reference chain: de.wyraz.tibberuploader.tibber.InternalAccountInfoResponse["errors"])
`

**Comment by micw** [comment]
Probier mal bitte mit dem build v0.3, sollte gleich fertig compiliert sein.

**Comment by 0x556c79** [comment]
Hallo @micw ich bekomme aktuell den Fehler den @theeogflip gemeldet hat.

Ich nutze docker mit `ghcr.com/micw/tibber-meter-uploader:master`. Habe aber auch schon `:latest` ausprobiert aber der container stürzt weiterhin ab.

```
:: Spring Boot ::               (v2.5.14)

2024-06-15 23:11:10.864  INFO 24 --- [           main] de.wyraz.tibberuploader.TibberUploader   : Starting TibberUploader v1.0.0-SNAPSHOT using Java 17-ea on tibber-meter-uploader with PID 24 (/tibber-meter-uploader-1.0.0-SNAPSHOT.jar started by root in /)
2024-06-15 23:11:10.876  INFO 24 --- [           main] de.wyraz.tibberuploader.TibberUploader   : No active profile set, falling back to 1 default profile: "default"
2024-06-15 23:11:17.282  INFO 24 --- [           main] de.wyraz.tibberuploader.TibberUploader   : Started TibberUploader in 9.508 seconds (JVM running for 12.264)
2024-06-15 23:11:22.627  INFO 24 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2024-06-15 23:11:22.707 ERROR 24 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:820) ~[spring-boot-2.5.14.jar!/:2.5.14]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:801) ~[spring-boot-2.5.14.jar!/:2.5.14]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:350) ~[spring-boot-2.5.14.jar!/:2.5.14]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1370) ~[spring-boot-2.5.14.jar!/:2.5.14]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1359) ~[spring-boot-2.5.14.jar!/:2.5.14]
	at de.wyraz.tibberuploader.TibberUploader.main(TibberUploader.java:28) ~[classes!/:1.0.0-SNAPSHOT]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[tibber-meter-uploader-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[tibber-meter-uploader-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[tibber-meter-uploader-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[tibber-meter-uploader-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
Caused by: java.net.UnknownHostException: app.tibber.com: Try again
	at java.base/java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method) ~[na:na]
	at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:932) ~[na:na]
	at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1517) ~[na:na]
	at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:851) ~[na:na]
	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1507) ~[na:na]
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1366) ~[na:na]
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1300) ~[na:na]
	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45) ~[httpclient-4.5.13.jar!/:4.5.13]
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112) ~[httpclient-4.5.13.jar!/:4.5.13]
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376) ~[httpclient-4.5.13.jar!/:4.5.13]
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393) ~[httpclient-4.5.13.jar!/:4.5.13]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[httpclient-4.5.13.jar!/:4.5.13]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186) ~[httpclient-4.5.13.jar!/:4.5.13]
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[httpclient-4.5.13.jar!/:4.5.13]
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.5.13.jar!/:4.5.13]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.13.jar!/:4.5.13]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[httpclient-4.5.13.jar!/:4.5.13]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108) ~[httpclient-4.5.13.jar!/:4.5.13]
	at de.wyraz.tibberuploader.tibber.TibberPrivateApi.login(TibberPrivateApi.java:84) ~[classes!/:1.0.0-SNAPSHOT]
	at de.wyraz.tibberuploader.tibber.TibberPrivateApi.getAccoutInfo(TibberPrivateApi.java:118) ~[classes!/:1.0.0-SNAPSHOT]
	at de.wyraz.tibberuploader.TibberUploader.uploadMissingReadings(TibberUploader.java:52) ~[classes!/:1.0.0-SNAPSHOT]
	at de.wyraz.tibberuploader.TibberUploader.run(TibberUploader.java:43) ~[classes!/:1.0.0-SNAPSHOT]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:817) ~[spring-boot-2.5.14.jar!/:2.5.14]
	... 13 common frames omitted
```

**Comment by 0x556c79** [comment]
Jetzt funktioniert es plötzlich wieder...
im übrigen mit dem image :master


```
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::               (v2.5.14)

2024-06-15 23:25:21.426  INFO 23 --- [           main] de.wyraz.tibberuploader.TibberUploader   : Starting TibberUploader v1.0.0-SNAPSHOT using Java 17-ea on tibber-meter-uploader with PID 23 (/tibber-meter-uploader-1.0.0-SNAPSHOT.jar started by root in /)
2024-06-15 23:25:21.462  INFO 23 --- [           main] de.wyraz.tibberuploader.TibberUploader   : No active profile set, falling back to 1 default profile: "default"
2024-06-15 23:25:28.086  INFO 23 --- [           main] de.wyraz.tibberuploader.TibberUploader   : Started TibberUploader in 9.883 seconds (JVM running for 12.638)
2024-06-15 23:25:33.449  INFO 23 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2024-06-15 23:25:33.526 ERROR 23 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:820) ~[spring-boot-2.5.14.jar!/:2.5.14]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:801) ~[spring-boot-2.5.14.jar!/:2.5.14]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:350) ~[spring-boot-2.5.14.jar!/:2.5.14]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1370) ~[spring-boot-2.5.14.jar!/:2.5.14]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1359) ~[spring-boot-2.5.14.jar!/:2.5.14]
	at de.wyraz.tibberuploader.TibberUploader.main(TibberUploader.java:28) ~[classes!/:1.0.0-SNAPSHOT]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[tibber-meter-uploader-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[tibber-meter-uploader-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[tibber-meter-uploader-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[tibber-meter-uploader-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
Caused by: java.net.UnknownHostException: app.tibber.com: Try again
	at java.base/java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method) ~[na:na]
	at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:932) ~[na:na]
	at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1517) ~[na:na]
	at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:851) ~[na:na]
	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1507) ~[na:na]
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1366) ~[na:na]
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1300) ~[na:na]
	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45) ~[httpclient-4.5.13.jar!/:4.5.13]
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112) ~[httpclient-4.5.13.jar!/:4.5.13]
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376) ~[httpclient-4.5.13.jar!/:4.5.13]
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393) ~[httpclient-4.5.13.jar!/:4.5.13]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[httpclient-4.5.13.jar!/:4.5.13]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186) ~[httpclient-4.5.13.jar!/:4.5.13]
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[httpclient-4.5.13.jar!/:4.5.13]
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.5.13.jar!/:4.5.13]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.13.jar!/:4.5.13]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[httpclient-4.5.13.jar!/:4.5.13]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108) ~[httpclient-4.5.13.jar!/:4.5.13]
	at de.wyraz.tibberuploader.tibber.TibberPrivateApi.login(TibberPrivateApi.java:84) ~[classes!/:1.0.0-SNAPSHOT]
	at de.wyraz.tibberuploader.tibber.TibberPrivateApi.getAccoutInfo(TibberPrivateApi.java:118) ~[classes!/:1.0.0-SNAPSHOT]
	at de.wyraz.tibberuploader.TibberUploader.uploadMissingReadings(TibberUploader.java:52) ~[classes!/:1.0.0-SNAPSHOT]
	at de.wyraz.tibberuploader.TibberUploader.run(TibberUploader.java:43) ~[classes!/:1.0.0-SNAPSHOT]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:817) ~[spring-boot-2.5.14.jar!/:2.5.14]
	... 13 common frames omitted

Application is running as root (UID 0). This is considered insecure.

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::               (v2.5.14)

2024-06-15 23:25:40.414  INFO 23 --- [           main] de.wyraz.tibberuploader.TibberUploader   : Starting TibberUploader v1.0.0-SNAPSHOT using Java 17-ea on tibber-meter-uploader with PID 23 (/tibber-meter-uploader-1.0.0-SNAPSHOT.jar started by root in /)
2024-06-15 23:25:40.428  INFO 23 --- [           main] de.wyraz.tibberuploader.TibberUploader   : No active profile set, falling back to 1 default profile: "default"
2024-06-15 23:25:47.075  INFO 23 --- [           main] de.wyraz.tibberuploader.TibberUploader   : Started TibberUploader in 9.799 seconds (JVM running for 12.236)
2024-06-15 23:25:52.483  INFO 23 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2024-06-15 23:25:52.563 ERROR 23 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:820) ~[spring-boot-2.5.14.jar!/:2.5.14]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:801) ~[spring-boot-2.5.14.jar!/:2.5.14]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:350) ~[spring-boot-2.5.14.jar!/:2.5.14]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1370) ~[spring-boot-2.5.14.jar!/:2.5.14]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1359) ~[spring-boot-2.5.14.jar!/:2.5.14]
	at de.wyraz.tibberuploader.TibberUploader.main(TibberUploader.java:28) ~[classes!/:1.0.0-SNAPSHOT]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[tibber-meter-uploader-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[tibber-meter-uploader-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[tibber-meter-uploader-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[tibber-meter-uploader-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
Caused by: java.net.UnknownHostException: app.tibber.com: Try again
	at java.base/java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method) ~[na:na]
	at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:932) ~[na:na]
	at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1517) ~[na:na]
	at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:851) ~[na:na]
	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1507) ~[na:na]
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1366) ~[na:na]
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1300) ~[na:na]
	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45) ~[httpclient-4.5.13.jar!/:4.5.13]
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112) ~[httpclient-4.5.13.jar!/:4.5.13]
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376) ~[httpclient-4.5.13.jar!/:4.5.13]
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393) ~[httpclient-4.5.13.jar!/:4.5.13]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[httpclient-4.5.13.jar!/:4.5.13]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186) ~[httpclient-4.5.13.jar!/:4.5.13]
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[httpclient-4.5.13.jar!/:4.5.13]
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.5.13.jar!/:4.5.13]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.13.jar!/:4.5.13]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[httpclient-4.5.13.jar!/:4.5.13]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108) ~[httpclient-4.5.13.jar!/:4.5.13]
	at de.wyraz.tibberuploader.tibber.TibberPrivateApi.login(TibberPrivateApi.java:84) ~[classes!/:1.0.0-SNAPSHOT]
	at de.wyraz.tibberuploader.tibber.TibberPrivateApi.getAccoutInfo(TibberPrivateApi.java:118) ~[classes!/:1.0.0-SNAPSHOT]
	at de.wyraz.tibberuploader.TibberUploader.uploadMissingReadings(TibberUploader.java:52) ~[classes!/:1.0.0-SNAPSHOT]
	at de.wyraz.tibberuploader.TibberUploader.run(TibberUploader.java:43) ~[classes!/:1.0.0-SNAPSHOT]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:817) ~[spring-boot-2.5.14.jar!/:2.5.14]
	... 13 common frames omitted

Application is running as root (UID 0). This is considered insecure.

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::               (v2.5.14)

2024-06-15 23:25:59.901  INFO 23 --- [           main] de.wyraz.tibberuploader.TibberUploader   : Starting TibberUploader v1.0.0-SNAPSHOT using Java 17-ea on tibber-meter-uploader with PID 23 (/tibber-meter-uploader-1.0.0-SNAPSHOT.jar started by root in /)
2024-06-15 23:25:59.915  INFO 23 --- [           main] de.wyraz.tibberuploader.TibberUploader   : No active profile set, falling back to 1 default profile: "default"
2024-06-15 23:26:06.617  INFO 23 --- [           main] de.wyraz.tibberuploader.TibberUploader   : Started TibberUploader in 9.834 seconds (JVM running for 12.737)
2024-06-15 23:26:09.095  INFO 23 --- [           main] ploader$$EnhancerBySpringCGLIB$$386b0d4b : Last entry is from today with reading 99903. Nothing to do for now.
```

**Comment by micw** [comment]
moin @0x556c79 

Ich denke, du hast da einen anderen Fehler:

```
java.net.UnknownHostException: app.tibber.com: Try again
```

Irgendwas stimmt da mit Deiner DNS-Auflösung im Docker nicht.A

**Comment by 0x556c79** [comment]
> moin @0x556c79
> 
> Ich denke, du hast da einen anderen Fehler:
> 
> ```
> java.net.UnknownHostException: app.tibber.com: Try again
> ```
> 
> Irgendwas stimmt da mit Deiner DNS-Auflösung im Docker nicht.

Danke.

Hat dann irgendwann wieder funktioniert.
